### ISSUE TITLE
Chart version is not used

### ISSUE THREAD

**Issue by gmenuel** [mumoshu/helm-x#30]
When setting chart versions helm-x doesn't use it. I've tracked the problem back to chartify which has been splitted from this repo a few weeks ago, and I've done a PR there : https://github.com/variantdev/chartify/pull/1

**Comment by mumoshu** [comment]
@gmenuel Thank you so much for reporting! This should have been fixed in recent versions of chartify. Sorry for not noticing your PR earlier..., but it did help me review my own commit that fixed the exact issue.

Please follow #31. Once merged, I'll cut a new helm-x release, which would close this issue.
